#include<iostream.h>
#include<conio.h>
class student
{
private:
   int Roll no;
   char Name[20];
public:
   void get()
   {
   cout<<"Enter The roll number";
   cin>>"roll no";
   cout<<"Enter the student name:";
   cin>>"student name";
   }
   void put()
   {
   cout<<"roll no";
   cout<<"Name";
   }
   main()
   {
   student[5];
   for(i=0;i<5;i++)
   {
   s(i).get();
   }
   for(i=0;i<5;i++)
   {
   s(i).put();
   }
   }




































